### ISSUE TITLE
aurpublish breaks after AUR password changed

### ISSUE THREAD

**Issue by goggle** [eli-schwartz/aurpublish#27]
After I have changed my AUR password, I can no longer use `aurpublish`.

I get this error:
```
git push using:  aur:kodi-addon-checker.git master
aur@aur.archlinux.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is there an easy way to fix this (maybe not an `aurpublish` issue)?

**Comment by brainpower** [comment]
AUR outage, not an aurpublish issue.
See: https://lists.archlinux.org/archives/list/aur-general@lists.archlinux.org/thread/Z4A6LKBQW4JYQL6P7ZMWT27SE4QQ4WKO/

**Comment by goggle** [comment]
@brainpower Thanks for the clarification, it works now again as expected.
