### ISSUE TITLE
[Enhancement] command to remove package

### ISSUE THREAD

**Issue by LW-archlinux** [eli-schwartz/aurpublish#9]
When someone stops maintaining an aur package they should be able to remove it from the split repo used by aurpublish.

Maybe a command  to do this could be added ?
A possible invocation : ```aurpublish -rm PACKAGE```

**Comment by eli-schwartz** [comment]
Why not just use `git rm -r PACKAGE; git commit`?

**Comment by LW-archlinux** [comment]
aurpublish description indicates it involves code to combine aur repos into one local repo on adding pacakges , then code to split the local repo into multiple repos for pushing . 

Is aurpublish code able to deal with such manual changes to its local repo ?

**Comment by eli-schwartz** [comment]
Yes, removing files with git rm is perfectly fine, other packages aren't affected by those changes and will continue to be split out and pushed as expected. Each directory is split out separately, so removing a directory is likewise split out separately -- or would, if it was still there to be split out.
